[[language]]
name = "typst"
language-servers = ["tinymist"]

[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.tinymist]
command = "tinymist"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"
