# ======
# Colors
# ======

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"
dim_foreground = "#a5abb6"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.search.focused_match]
foreground = "#2e3440"
background = "#a3be8c"

[colors.hints.start]
foreground = "#2e3440"
background = "#ebcb8b"

[colors.hints.end]
foreground = "#2e3440"
background = "#d8dee9"

[colors.footer_bar]
background = "#2e3440"
foreground = "#d8dee9"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

# ===
# Env
# ===

[env]
TERM = "xterm-256color"

# ======
# Window
# ======

[window]
padding = { x = 2, y = 2 } # default 0, 0
dynamic_padding = true # default false
decorations = "None" # default "Full"
startup_mode = "Maximized" # default "Windowed"

# ====
# Font
# ====

[font]
size = 13 # default 11.25
offset.y = 2 # default 0
normal.family = "JetBrainsMono NF"

# ======
# Cursor
# ======

[cursor]
blink_interval = 500 # default 750 

[cursor.style]
shape = "Beam" # default "Block"
blinking = "On" # default "Off"

# =========
# Selection
# =========

[selection]
save_to_clipboard = true # default false

# =================
# Keyboard Bindings
# =================

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]

# ==============
# Mouse Bindings
# ==============

[mouse]
bindings = [
  { mouse = "Right", mods = "Control", action = "Paste" },
]
