# [colors.bar]
# background = "#434c5e"
# foreground = "#d8dee9"

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"

[keyboard.bindings.command]
program = "alacritty"

[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["-e", "sh", "-c", "topgrade"]
program = "alacritty"

[[keyboard.bindings]]
key = "P"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["-e", "sh", "-c", "pyupdate"]
program = "alacritty"

[[keyboard.bindings]]
key = "R"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["-e", "sh", "-c", "cargo run"]
program = "alacritty"

[window.dimensions]
columns = 300
lines = 100

[window.padding]
x = 12
y = 12
