[helpers]

[default]
depends = []

[default.files]
# dot_bashrc = ""
# dot_config = ""

[default.variables]

[settings]
default_target_type = "template"

[alacritty.files]
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

