[helpers]

[default]
depends = []

[default.files]
# dot_bashrc = ""
# dot_config = ""

[default.variables]

[settings]
default_target_type = "automatic"

[alacritty.files]
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[zellij.files]
"zellij/config.kdl" = "~/.config/zellij/config.kdl"

[helix.files]
"helix/config.toml" = "~/.config/helix/config.toml"
"helix/languages.toml" = "~/.config/helix/languages.toml"

[zathura.files]
"zathura/zathurarc" = "~/.config/zathura/zathurarc"

[mpv.files]
"mpv/mpv.conf" = "~/.config/mpv/mpv.conf"
"mpv/input.conf" = "~/.config/mpv/input.conf"
"mpv/scripts/skipsilence.lua" = "~/.config/mpv/scripts/skipsilence.lua"

[yt-dlp.files]
"yt-dlp/config" = "~/.config/yt-dlp/config"

[git.files]
"git/config" = "~/.config/git/config"

